version: 2
jobs:
   build:
     docker:
       - image: koppor/texlive
     steps:
       - checkout
       - run: latexmk paper-conference.tex
       - run: latexmk paper-conference-minted.tex
       - run: latexmk paper-conference-compsoc.tex
       - run: mkdir build && cp -r README.md paper*.pdf .github/_config.yml build/
       - store_artifacts:
           path: build/
       - run: if [ "$CIRCLE_BRANCH" == "master" ]; then .circleci/deploy-ghpages.sh build/; fi
